### ISSUE TITLE
interpose didn't work

### ISSUE THREAD

**Issue by stathissideris** [borkdude/re-find#2]
I was expecting to get `interpose` for this, but I didn't.

```
0 [1 2 3 4 5]
(1 0 2 0 3 0 4 0 5)
```

**Comment by borkdude** [comment]
Thanks! This is likely due to a missing spec in speculative. I'll add it soon.

**Comment by borkdude** [comment]
https://re-find.it/?args=0%20%5B1%202%203%5D&ret=coll%3f
